In [1]:
import torch
import numpy as np

Create array with numpy

In [2]:
array=[[1,2,3],[4,5,6]]

In [4]:
array2=np.array(array)

In [5]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
array2.shape


(2, 3)

In [7]:
array2.size

6

Create shorted array with numpy

In [10]:
short_arrat=np.arange(1,10)

In [11]:
short_arrat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
zero=np.zeros(5)

In [13]:
zero

array([0., 0., 0., 0., 0.])

In [14]:
one=np.ones(4)

In [15]:
one

array([1., 1., 1., 1.])

In [18]:
half=np.array(one)/2

In [19]:
half

array([0.5, 0.5, 0.5, 0.5])

create matris

In [20]:
birim= np.eye(4)

In [21]:
birim

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

create random number between 0 and 1 

In [24]:
random=np.random.rand(9)

In [25]:
random

array([0.59049105, 0.27560092, 0.84841383, 0.52759862, 0.94259119,
       0.2423803 , 0.62461886, 0.60120634, 0.63858022])

create intiger with np

In [50]:
arry=np.random.randint(2,15,10)

In [51]:
arry

array([ 6, 12,  8,  9, 14,  4, 10, 14,  6, 11])

if we want create a stabhil array we should use the seed

In [52]:
stabhil=np.random.seed(25)

In [54]:
reshapeiint=arry.reshape(2,5)

In [55]:
reshapeiint

array([[ 6, 12,  8,  9, 14],
       [ 4, 10, 14,  6, 11]])

find the max value in array

In [56]:
max=np.max(reshapeiint)

In [57]:
max

14

In [60]:
indis=np.argmax(reshapeiint)

In [61]:
indis

4

aarray slace

In [62]:
slace=reshapeiint[1:5]

In [63]:
slace

array([[ 4, 10, 14,  6, 11]])

copiing the array

In [64]:
slace2=slace.copy()

In [65]:
slace2

array([[ 4, 10, 14,  6, 11]])

In [76]:
array2[1]

array([4, 5, 6])

In [77]:
array2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

firt 2 rows after firs colons

In [81]:
array2[:2,1:]

array([[2, 3],
       [5, 6]])

In [82]:
array3=np.arange(1,11)

In [83]:
array3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
array3>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

sum with numpy

In [85]:
array2.sum(axis=0)

array([5, 7, 9])

In [86]:
array2.sum(axis=1)

array([ 6, 15])