In [8]:
import torch as tr
import pandas as pd
import numpy as np

Torch tensor and numpy transfer

In [9]:
array=np.array([1,2,3,4,5])

In [10]:
array

array([1, 2, 3, 4, 5])

if we use this methods when our numpy matris be changed ,the torch tensor Will be chanced to

In [13]:
trarray=tr.from_numpy(array)

In [16]:
trarray.dtype

torch.int32

In [17]:
type(trarray)

torch.Tensor

In [18]:
trarray2 = tr.as_tensor(array)

In [19]:
trarray2

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [20]:
array[0]=255

In [22]:
trarray2

tensor([255,   2,   3,   4,   5], dtype=torch.int32)

In [21]:
trarray

tensor([255,   2,   3,   4,   5], dtype=torch.int32)

İf we use this metod, our torch tensor will not be changed

In [23]:
narray=np.array([6,7,8,9])

In [24]:
staytorch=tr.tensor(narray)

In [25]:
staytorch


tensor([6, 7, 8, 9], dtype=torch.int32)

In [26]:
narray[0]=999

In [27]:
staytorch

tensor([6, 7, 8, 9], dtype=torch.int32)

The torch tensor converting to float

In [28]:
floattensor=tr.FloatTensor(narray)

In [29]:
floattensor

tensor([999.,   7.,   8.,   9.])

In [41]:
torch.rand(4,2)

tensor([[0.9517, 0.5610],
        [0.1973, 0.6751],
        [0.6050, 0.5701],
        [0.1708, 0.7229]])

In [43]:
y=tr.randint(low=2,high=11,size=(5,5))

In [44]:
y

tensor([[ 2,  9,  5, 10,  2],
        [ 9,  2,  8,  9,  5],
        [ 9,  4,  2,  9,  4],
        [ 2,  3,  7,  5,  6],
        [10,  3,  2,  3,  7]])

In [46]:
x=tr.randint_like(y,low=2,high=11)

In [47]:
x

tensor([[ 3,  4,  9,  9,  9],
        [ 6,  9,  7,  5,  7],
        [ 5,  8,  2,  9,  8],
        [ 3,  9,  9,  9, 10],
        [ 8, 10,  6,  2,  2]])